# Generated by Django 3.0.3 on 2020-07-23 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Home', '0002_contact_timestamp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='contact',
            new_name='content',
        ),
    ]
